#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 800




#define VISUAL_SCALE 0.80
#define GAME_WINDOW_WIDTH (WINDOW_WIDTH * VISUAL_SCALE)
#define GAME_WINDOW_HEIGHT (WINDOW_HEIGHT * VISUAL_SCALE)

#define FPS 30
#define FRAME_TARGET_TIME (1000/FPS)
#define SPEED 200
#define SNAKE_SIZE_CAP 200

#define FOOD_SIZE 15
#define SNAKE_SIZE 15